//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPKthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMIN()
        {
            this.PHANQUYENs = new HashSet<PHANQUYEN>();
        }
    
        public string MAADMIN { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string DIENTHOAI { get; set; }
        public Nullable<int> MALOAI { get; set; }
        public string TENDN { get; set; }
        public string MATKHAU { get; set; }
        public string AVATAR { get; set; }
        public string EMAIL { get; set; }
    
        public virtual LOAITKADMIN LOAITKADMIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
