//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPKthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINH
    {
        public int MAHINH { get; set; }
        public string MASP { get; set; }
        public string HINH1 { get; set; }
        public Nullable<bool> ANHIEN { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
