//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPKthucung.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTDONDATHANGs = new HashSet<CTDONDATHANG>();
            this.GIAMGIAs = new HashSet<GIAMGIA>();
            this.HINHs = new HashSet<HINH>();
            this.KICHTHUOCs = new HashSet<KICHTHUOC>();
            this.PHIEUNHAPKHOes = new HashSet<PHIEUNHAPKHO>();
        }
    
        public string MASP { get; set; }
        public string TENSP { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,##0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> DONGIAMUA { get; set; }
        [DisplayFormat(DataFormatString = "{0:#,##0}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> DONGIABAN { get; set; }
        public string MATH { get; set; }
        public string MALOAI { get; set; }
        public string MAMAUSAC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public string THANHTOANON { get; set; }
        public Nullable<bool> ANHHIEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDONDATHANG> CTDONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAMGIA> GIAMGIAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINH> HINHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KICHTHUOC> KICHTHUOCs { get; set; }
        public virtual LOAI LOAI { get; set; }
        public virtual MAUSAC MAUSAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAPKHO> PHIEUNHAPKHOes { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
    }
}
