//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPKthucung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int MATHAMSO { get; set; }
        public string TENTHAMSO { get; set; }
        public int SOLUONG { get; set; }
        public string KIEUDULIEU { get; set; }
        public bool TINHTRANG { get; set; }
    }
}
